# Generated by Django 6.0.3 on 2026-03-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='fertility',
            field=models.CharField(choices=[('H', 'High'), ('N', 'Normal'), ('L', 'Low')], default='H', max_length=6),
            preserve_default=False,
        ),
    ]
