# Generated by Django 6.0.3 on 2026-03-26 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('personality', models.CharField(max_length=55)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('initial_age', models.IntegerField(default=0)),
            ],
        ),
    ]
