# Generated by Django 6.0.3 on 2026-03-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0002_npc_fertility'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='sexual_orientation',
            field=models.CharField(choices=[('hetero', 'Heterosexual'), ('gay', 'Gay'), ('bi', 'Bisexual'), ('other', 'Other')], default='hetero', max_length=10),
        ),
    ]
