# Generated by Django 6.0.3 on 2026-03-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0004_npc_latitude_npc_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='longitude',
        ),
    ]
