# Generated by Django 6.0.3 on 2026-03-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0005_remove_npc_latitude_remove_npc_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='latitude',
            field=models.FloatField(default=49.2992),
        ),
        migrations.AddField(
            model_name='npc',
            name='longitude',
            field=models.FloatField(default=19.9496),
        ),
    ]
