# Generated by Django 6.0.3 on 2026-03-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0006_npc_latitude_npc_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='fitness_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='npc',
            name='initial_age',
            field=models.IntegerField(),
        ),
    ]
