# Generated by Django 6.0.3 on 2026-04-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0007_npc_fitness_level_alter_npc_initial_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='npc',
            old_name='created_at',
            new_name='born_at',
        ),
        migrations.AddField(
            model_name='npc',
            name='aggression_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='charisma_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='empathy_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='energy_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='npc',
            name='happiness_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='health_level',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='npc',
            name='intelligence_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='introversion_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='morality_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='stress_level',
            field=models.IntegerField(default=0),
        ),
    ]
