# Generated by Django 6.0.3 on 2026-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0008_rename_created_at_npc_born_at_npc_aggression_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='died_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='npc',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
    ]
