# Generated by Django 6.0.3 on 2026-04-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0009_npc_died_at_npc_is_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='initial_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
