# Generated by Django 6.0.3 on 2026-04-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0010_alter_npc_initial_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_father', to='npc.npc'),
        ),
        migrations.AddField(
            model_name='npc',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_mother', to='npc.npc'),
        ),
    ]
