# Generated by Django 6.0.3 on 2026-04-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0011_npc_father_npc_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='is_adventurous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='npc',
            name='introversion_level',
            field=models.IntegerField(default=50),
        ),
    ]
