# Generated by Django 6.0.3 on 2026-04-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0012_npc_is_adventurous_alter_npc_introversion_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='previous_partners',
            field=models.ManyToManyField(blank=True, related_name='partnered_with', to='npc.npc'),
        ),
    ]
