# Generated by Django 6.0.3 on 2026-04-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0013_npc_previous_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='degenerative_condition',
            field=models.CharField(choices=[('none', 'None'), ('sociopath', 'Sociopath'), ('psychopath', 'Psychopath'), ('pedophile', 'Pedophile'), ('paranoid', 'Paranoid'), ('narcissist', 'Narcissist')], default='none', max_length=20),
        ),
    ]
