# Generated by Django 6.0.3 on 2026-04-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0014_npc_degenerative_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='has_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='npc',
            name='happiness_level',
            field=models.IntegerField(default=50),
        ),
    ]
