# Generated by Django 6.0.3 on 2026-04-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0015_npc_has_kids_alter_npc_happiness_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
