# Generated by Django 6.0.3 on 2026-04-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0016_npc_is_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='personality_traits',
            field=models.JSONField(default=list, null=True),
        ),
    ]
