# Generated by Django 6.0.3 on 2026-04-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0017_npc_personality_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='personality_traits',
            field=models.JSONField(default=list),
        ),
    ]
