# Generated by Django 6.0.3 on 2026-04-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0018_alter_npc_personality_traits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='npc',
            name='personality',
        ),
    ]
