# Generated by Django 6.0.3 on 2026-04-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0019_remove_npc_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='creativity_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='npc',
            name='occupation',
            field=models.CharField(default='Unemployed', max_length=50),
        ),
        migrations.AddField(
            model_name='npc',
            name='wealth',
            field=models.IntegerField(default=0),
        ),
    ]
