# Generated by Django 6.0.3 on 2026-04-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0020_npc_creativity_level_npc_occupation_npc_wealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='job_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='npc',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
