# Generated by Django 6.0.3 on 2026-04-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0022_alter_npc_aggression_level_alter_npc_charisma_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='latitude',
            field=models.FloatField(db_index=True, default=49.2992),
        ),
        migrations.AlterField(
            model_name='npc',
            name='longitude',
            field=models.FloatField(db_index=True, default=19.9496),
        ),
    ]
