# Generated by Django 6.0.3 on 2026-04-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0023_alter_npc_latitude_alter_npc_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='latitude',
            field=models.FloatField(default=49.2992),
        ),
        migrations.AlterField(
            model_name='npc',
            name='longitude',
            field=models.FloatField(default=19.9496),
        ),
    ]
