# Generated by Django 6.0.3 on 2026-04-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0024_alter_npc_latitude_alter_npc_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='spawn_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='npc',
            name='degenerative_condition',
            field=models.CharField(choices=[('none', 'None'), ('sociopath', 'Sociopath'), ('psychopath', 'Psychopath'), ('paranoid', 'Paranoid'), ('narcissist', 'Narcissist')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='npc',
            name='fertility',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('N', 'Normal'), ('L', 'Low')], max_length=6),
        ),
        migrations.AlterField(
            model_name='npc',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='npc',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
